# Get the full dataset

### import

In [2]:
import pandas as pd
import numpy as np

## Merging both dataset

In [97]:
cleaned_data = pd.read_csv("DATA/cleaned_data.csv", index_col = 0)
cleaned_data = cleaned_data.groupby(["CompanyName", "Device", "Market", " SubMarket", "PeriodCode"]).sum().reset_index()
cleaned_data.rename(columns = {" SubMarket" : "SubMarket", "PeriodCode" : "Year"}, inplace = True)
cleaned_data.Year = cleaned_data.Year.apply( lambda x: int(x[1:]))
#cleaned_data.drop("CompanyName", axis = 1, inplace = True)
cleaned_data

,CompanyName,Device,Market,SubMarket,Year,Value
0,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2018,1.349324
1,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2019,1.491100
2,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2020,1.362700
3,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2021,2.164928
4,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2022,2.637800
...,...,...,...,...,...,...
19665,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2020,0.809700
19666,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2021,1.271038
19667,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2022,1.229600
19668,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2023,1.182734
19669,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2024,1.173666

In [98]:
market_spend = pd.read_csv("DATA/Market.csv")
market_spend

,Market,Submarket,Device,Year,Region,Market size
0,Automotive Electronics Categories,ADAS,Amplifier/Comparator,2008,Americas,0.424
1,Automotive Electronics Categories,ADAS,Amplifier/Comparator,2008,Asia & Oceania (excl. Japan),0.246
2,Automotive Electronics Categories,ADAS,Amplifier/Comparator,2008,EMEA,0.678
3,Automotive Electronics Categories,ADAS,Amplifier/Comparator,2008,Japan,0.421
4,Automotive Electronics Categories,ADAS,Amplifier/Comparator,2008,Worldwide,1.769
...,...,...,...,...,...,...
32495,Wireless Communications Categories,Wireless LAN Equipment,Voltage Regulator/Reference,2027,Americas,0.000
32496,Wireless Communications Categories,Wireless LAN Equipment,Voltage Regulator/Reference,2027,Asia & Oceania (excl. Japan),0.000
32497,Wireless Communications Categories,Wireless LAN Equipment,Voltage Regulator/Reference,2027,EMEA,0.000
32498,Wireless Communications Categories,Wireless LAN Equipment,Voltage Regulator/Reference,2027,Japan,0.000
32499,Wireless Communications Categories,Wireless LAN Equipment,Voltage Regulator/Reference,2027,Worldwide,0.000

In [99]:
dict_map = {('Automotive Electronics Categories', 'ADAS'): ('Automotive', 'Auto ADAS'), ('Automotive Electronics Categories', 'Body & Convenience'): ('Automotive', 'Connected Consumer'), ('Automotive Electronics Categories', 'Chassis & Safety'): ('Automotive', 'Test & Measurement'), ('Automotive Electronics Categories', 'Connectivity & Telematics'): ('Automotive', 'Test & Measurement'), ('Automotive Electronics Categories', 'Hybrid & Electric Drive Train'): ('Automotive', 'DC Network & Threat Mitigation'), ('Automotive Electronics Categories', 'Infotainment & Cluster'): ('Automotive', 'Auto Infotainment'), ('Automotive Electronics Categories', 'Other Automotive'): ('Automotive', 'Other Storage'), ('Automotive Electronics Categories', 'Powertrain & Vehicle Dynamics'): ('Automotive', 'Power & Energy'), ('Computing & Data Storage Categories', 'Data Center Servers'): ('Computer Peripherals & Storage', 'Data Center Servers'), ('Computing & Data Storage Categories', 'Desktop PCs'): ('Computer Peripherals & Storage', 'Desktop PCs'), ('Computing & Data Storage Categories', 'Flash Storage Cards'): ('Computer Peripherals & Storage', 'Flash Cards/Drives'), ('Computing & Data Storage Categories', 'Hard Disk Drives'): ('Computer Peripherals & Storage', 'Flash Cards/Drives'), ('Computing & Data Storage Categories', 'Notebook PCs'): ('Computer Peripherals & Storage', 'Notebook PCs'), ('Computing & Data Storage Categories', 'Other Computing'): ('Computer Peripherals & Storage', 'Other Computer Products'), ('Computing & Data Storage Categories', 'Other Data Storage'): ('Computer Peripherals & Storage', 'Other Storage'), ('Computing & Data Storage Categories', 'Other Peripherals'): ('Computer Peripherals & Storage', 'Other Peripherals'), ('Computing & Data Storage Categories', 'Smart Cards'): ('Computer Peripherals & Storage', 'Smart Cards'), ('Computing & Data Storage Categories', 'Solid-State Drives'): ('Computer Peripherals & Storage', 'Data Center Servers'), ('Computing & Data Storage Categories', 'Tablet PCs'): ('Computer Peripherals & Storage', 'Tablet PCs'), ('Computing & Data Storage Categories', 'USB Flash Drive'): ('Computer Peripherals & Storage', 'Flash Cards/Drives'), ('Consumer Electronics Categories', 'Fitness & Wellness Wearable Electronics'): ('Computer Platforms', 'Test & Measurement'), ('Consumer Electronics Categories', 'LCD TV'): ('Computer Platforms', 'TV'), ('Consumer Electronics Categories', 'Major Home Appliances'): ('Computer Platforms', 'Appliance'), ('Consumer Electronics Categories', 'OLED TV'): ('Computer Platforms', 'TV'), ('Consumer Electronics Categories', 'Other Audio/Video'): ('Computer Platforms', 'Other Storage'), ('Consumer Electronics Categories', 'Other Consumer Electronics'): ('Computer Platforms', 'Other Consumer'), ('Consumer Electronics Categories', 'Set-Top Boxes'): ('Computer Platforms', 'Desktop PCs'), ('Consumer Electronics Categories', 'Smart Speakers & Digital Assistants'): ('Computer Platforms', 'Smart Cards'), ('Consumer Electronics Categories', 'Smart Watches'): ('Computer Platforms', 'Smart Cards'), ('Consumer Electronics Categories', 'VR Headsets'): ('Computer Platforms', 'Handset'), ('Consumer Electronics Categories', 'Video Game Consoles'): ('Computer Platforms', 'Video Games'), ('Industrial Electronics Categories', 'Automation'): ('Industrial', 'Auto Powertrain'), ('Industrial Electronics Categories', 'Building & Home Control'): ('Industrial', 'Manufacturing Equipment'), ('Industrial Electronics Categories', 'Lighting'): ('Industrial', 'Manufacturing Equipment'), ('Industrial Electronics Categories', 'Medical Electronics'): ('Industrial', 'Media Tablets'), ('Industrial Electronics Categories', 'Military & Civil Aerospace'): ('Industrial', 'Military/Aerospace'), ('Industrial Electronics Categories', 'Other Industrial'): ('Industrial', 'Other Industrial'), ('Industrial Electronics Categories', 'Power & Energy'): ('Industrial', 'Power & Energy'), ('Industrial Electronics Categories', 'Security & Video Surveillance'): ('Industrial', 'Test & Measurement'), ('Industrial Electronics Categories', 'Test & Measurement'): ('Industrial', 'Test & Measurement'), ('Wired Communications Categories', 'Broadcast & Streaming Video'): ('Wired Communications', 'Test & Measurement'), ('Wired Communications Categories', 'Cable Aggregation Equipment'): ('Wired Communications', 'Manufacturing Equipment'), ('Wired Communications Categories', 'Cable CPE'): ('Wired Communications', 'Tablet PCs'), ('Wired Communications Categories', 'Carrier Ethernet Switches & Routers'): ('Wired Communications', 'Other Computer Products'), ('Wired Communications Categories', 'DSL Aggregation Equipment'): ('Wired Communications', 'Manufacturing Equipment'), ('Wired Communications Categories', 'DSL CPE'): ('Wired Communications', 'Desktop PCs'), ('Wired Communications Categories', 'Data Center Network Switches'): ('Wired Communications', 'Data Center Servers'), ('Wired Communications Categories', 'Enterprise Ethernet Switches & Routers'): ('Wired Communications', 'Enterprise/SOHO'), ('Wired Communications Categories', 'Enterprise UC & Voice'): ('Wired Communications', 'Enterprise/SOHO'), ('Wired Communications Categories', 'FTTH Aggregation Equipment'): ('Wired Communications', 'Manufacturing Equipment'), ('Wired Communications Categories', 'FTTH CPE'): ('Wired Communications', 'Tablet PCs'), ('Wired Communications Categories', 'Low-Tier Consumer/SOHO Routers'): ('Wired Communications', 'Other Consumer'), ('Wired Communications Categories', 'Optical Equipment'): ('Wired Communications', 'Manufacturing Equipment'), ('Wired Communications Categories', 'Other Wired Communications'): ('Wired Communications', 'Other Wired'), ('Wired Communications Categories', 'Threat Mitigation Products'): ('Wired Communications', 'DC Network & Threat Mitigation'), ('Wireless Communications Categories', 'Gray Market Handsets'): ('Wireless Communications', 'Handset'), ('Wireless Communications Categories', 'High-Tier Smartphone'): ('Wireless Communications', 'Other Peripherals'), ('Wireless Communications Categories', 'Low-Tier Smartphone'): ('Wireless Communications', 'Power & Energy'), ('Wireless Communications Categories', 'M2M Modules'): ('Wireless Communications', 'Media Tablets'), ('Wireless Communications Categories', 'Media Tablets'): ('Wireless Communications', 'Media Tablets'), ('Wireless Communications Categories', 'Mid-Tier Smartphone'): ('Wireless Communications', 'Video Games'), ('Wireless Communications Categories', 'Mobile Comm Infrastructure'): ('Wireless Communications', 'Infrastructure'), ('Wireless Communications Categories', 'Mobile Phone (ULCH, Entry, Feature)'): ('Wireless Communications', 'Military/Aerospace'), ('Wireless Communications Categories', 'Other Wireless Communications'): ('Wireless Communications', 'Other Wireless'), ('Wireless Communications Categories', 'Wireless LAN Equipment'): ('Wireless Communications', 'Manufacturing Equipment')}

In [100]:
#Nb of keys
print(len(dict_map.keys()))

#Rename the market and submarket

def remapping(market, submarket):
    key = (market, submarket)
    return dict_map[key][0], dict_map[key][1]

market_spend.Market, market_spend.Submarket = zip(*market_spend.apply(lambda x : remapping(x.Market, x.Submarket), axis = 1))
market_spend.rename(columns = {"Submarket" : "SubMarket"}, inplace = True)
market_spend

65

,Market,SubMarket,Device,Year,Region,Market size
0,Automotive,Auto ADAS,Amplifier/Comparator,2008,Americas,0.424
1,Automotive,Auto ADAS,Amplifier/Comparator,2008,Asia & Oceania (excl. Japan),0.246
2,Automotive,Auto ADAS,Amplifier/Comparator,2008,EMEA,0.678
3,Automotive,Auto ADAS,Amplifier/Comparator,2008,Japan,0.421
4,Automotive,Auto ADAS,Amplifier/Comparator,2008,Worldwide,1.769
...,...,...,...,...,...,...
32495,Wireless Communications,Manufacturing Equipment,Voltage Regulator/Reference,2027,Americas,0.000
32496,Wireless Communications,Manufacturing Equipment,Voltage Regulator/Reference,2027,Asia & Oceania (excl. Japan),0.000
32497,Wireless Communications,Manufacturing Equipment,Voltage Regulator/Reference,2027,EMEA,0.000
32498,Wireless Communications,Manufacturing Equipment,Voltage Regulator/Reference,2027,Japan,0.000
32499,Wireless Communications,Manufacturing Equipment,Voltage Regulator/Reference,2027,Worldwide,0.000

In [101]:
market_spend = market_spend[(market_spend.Region == "Worldwide")]
market_spend.drop("Region", axis = 1, inplace = True)
market_spend

<ipython-input-101-612f2c74d230>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  market_spend.drop("Region", axis = 1, inplace = True)

,Market,SubMarket,Device,Year,Market size
4,Automotive,Auto ADAS,Amplifier/Comparator,2008,1.769
9,Automotive,Auto ADAS,Amplifier/Comparator,2009,1.390
14,Automotive,Auto ADAS,Amplifier/Comparator,2010,3.401
19,Automotive,Auto ADAS,Amplifier/Comparator,2011,5.911
24,Automotive,Auto ADAS,Amplifier/Comparator,2012,7.250
...,...,...,...,...,...
32479,Wireless Communications,Manufacturing Equipment,Voltage Regulator/Reference,2023,0.000
32484,Wireless Communications,Manufacturing Equipment,Voltage Regulator/Reference,2024,0.000
32489,Wireless Communications,Manufacturing Equipment,Voltage Regulator/Reference,2025,0.000
32494,Wireless Communications,Manufacturing Equipment,Voltage Regulator/Reference,2026,0.000
32499,Wireless Communications,Manufacturing Equipment,Voltage Regulator/Reference,2027,0.000

In [102]:
merged_dataset = cleaned_data.merge(market_spend, how = 'left', on = ['Market', "SubMarket", "Device", "Year"])
merged_dataset = merged_dataset.groupby(["CompanyName", "Device", "Market", "SubMarket", "Year", "Value"]).sum().reset_index()
merged_dataset.rename(columns = {"Market size" : "Spendings"}, inplace = True)
merged_dataset

,CompanyName,Device,Market,SubMarket,Year,Value,Spendings
0,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2018,1.349324,63.254
1,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2019,1.491100,58.716
2,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2020,1.362700,61.471
3,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2021,2.164928,84.752
4,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2022,2.637800,88.482
...,...,...,...,...,...,...,...
19665,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2020,0.809700,430.000
19666,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2021,1.271038,546.000
19667,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2022,1.229600,517.000
19668,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2023,1.182734,441.999
19669,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2024,1.173666,421.999

In [103]:
spend_bydevice = merged_dataset[["Device", "Year", "Spendings"]].groupby(["Device", "Year"]).sum().reset_index().rename(columns = {"Spendings" : "DevSpends"})
spend_bymarket= merged_dataset[["Market",  "Year","Spendings"]].groupby(["Market", "Year"]).sum().reset_index().rename(columns = {"Spendings" : "MarketSpends"})
spend_bysubmarket = merged_dataset[["SubMarket", "Year", "Spendings"]].groupby(["SubMarket", "Year"]).sum().reset_index().rename(columns = {"Spendings" : "SubMarketSpends"})

In [104]:
spend_bydevice

                            Device  Year   DevSpends
0             Amplifier/Comparator  2018   33009.633
1             Amplifier/Comparator  2019   31492.062
2             Amplifier/Comparator  2020   30177.791
3             Amplifier/Comparator  2021   39871.494
4             Amplifier/Comparator  2022   44223.186
5             Amplifier/Comparator  2023   47897.781
6             Amplifier/Comparator  2024   48501.823
7   Analog Application Specific IC  2018  309095.924
8   Analog Application Specific IC  2019  299683.612
9   Analog Application Specific IC  2020  328933.757
10  Analog Application Specific IC  2021  392841.063
11  Analog Application Specific IC  2022  421467.305
12  Analog Application Specific IC  2023  387035.438
13  Analog Application Specific IC  2024  381760.641
14                 Data Converters  2018   37411.156
15                 Data Converters  2019   35659.038
16                 Data Converters  2020   34241.622
17                 Data Converters  2021   46699.434
18                 Data Converters  2022   51527.941
19                 Data Converters  2023   53146.556
20                 Data Converters  2024   55669.719
21                       Interface  2018   40841.875
22                       Interface  2019   38870.652
23                       Interface  2020   40817.136
24                       Interface  2021   49761.951
25                       Interface  2022   53667.156
26                       Interface  2023   56277.042
27                       Interface  2024   60253.922
28     Voltage Regulator/Reference  2018  101291.063
29     Voltage Regulator/Reference  2019   99479.515
30     Voltage Regulator/Reference  2020  103400.887
31     Voltage Regulator/Reference  2021  128025.114
32     Voltage Regulator/Reference  2022  138115.036
33     Voltage Regulator/Reference  2023  134477.314
34     Voltage Regulator/Reference  2024  142579.443

In [105]:
merged_dataset = merged_dataset.merge(spend_bydevice, how = 'left', on = ["Device", "Year"])
merged_dataset = merged_dataset.merge(spend_bymarket, how = 'left', on = ["Market", "Year"])
merged_dataset = merged_dataset.merge(spend_bysubmarket, how = 'left', on = ["SubMarket", "Year"])
merged_dataset

,CompanyName,Device,Market,SubMarket,Year,Value,Spendings,DevSpends,MarketSpends,SubMarketSpends
0,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2018,1.349324,63.254,33009.633,202444.977,52627.040
1,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2019,1.491100,58.716,31492.062,190906.584,48480.544
2,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2020,1.362700,61.471,30177.791,197047.823,54473.792
3,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2021,2.164928,84.752,39871.494,245502.837,72134.752
4,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2022,2.637800,88.482,44223.186,272578.716,80606.752
...,...,...,...,...,...,...,...,...,...,...
19665,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2020,0.809700,430.000,103400.887,212485.648,104836.024
19666,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2021,1.271038,546.000,128025.114,255121.403,125907.267
19667,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2022,1.229600,517.000,138115.036,263200.273,122225.289
19668,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2023,1.182734,441.999,134477.314,214442.956,100072.931
19669,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2024,1.173666,421.999,142579.443,195364.035,92275.977

## Addition of the Financial Data

In [106]:
merged_dataset.rename(columns = {"CompanyName" : "Company"}, inplace = True)

In [107]:
comp_map = pd.read_csv("CompanyMapping.csv", delimiter= ";", encoding='unicode_escape')
comp_map = comp_map.set_index("Company name in financial data").to_dict()["Company name in spend tracker"]
companies_available = comp_map.keys()

In [108]:
def mapping_companies(x):
    if x in companies_available:
        return comp_map[x]
    else :
        return None

In [109]:
ebitda = pd.read_csv("DATA/ebitda_complete.csv")
ebitda.Company = ebitda.Company.apply(mapping_companies)
ebitda = ebitda[~ebitda['Company'].isnull()]
ebitda["Ebitda_1"] = ebitda.groupby('Company')['Ebitda'].shift(1)
ebitda["Ebitda_2"] = ebitda.groupby('Company')['Ebitda'].shift(2)
ebitda

            Company  Year        Ebitda  Ebitda_1  Ebitda_2
12    Cisco Systems  2016  14721.000000       NaN       NaN
13    Cisco Systems  2017  14460.000000  14721.00       NaN
14    Cisco Systems  2018  15307.000000  14460.00  14721.00
15    Cisco Systems  2019  16205.000000  15307.00  14460.00
16    Cisco Systems  2020  15236.000000  16205.00  15307.00
...             ...   ...           ...       ...       ...
2071         Xiaomi  2023   2419.430000   1166.90   3012.20
2072         Xiaomi  2024   2557.860000   2419.43   1166.90
2073         Xiaomi  2025  50536.690000   2557.86   2419.43
2074         Xiaomi  2026   3859.150000  50536.69   2557.86
2075         Xiaomi  2027   8431.042857   3859.15  50536.69

[1116 rows x 5 columns]

In [110]:
cogs = pd.read_csv("DATA/cogs_final.csv")
cogs.Company = cogs.Company.apply(mapping_companies)
cogs = cogs[~cogs['Company'].isnull()]
cogs.rename(columns = {"Value" : "Cogs"}, inplace = True)
cogs["Cogs_1"] = cogs.groupby('Company')['Cogs'].shift(1)
cogs["Cogs_2"] = cogs.groupby('Company')['Cogs'].shift(2)
cogs

            Company  Year          Cogs        Cogs_1        Cogs_2
12    Cisco Systems  2016  17663.000000           NaN           NaN
13    Cisco Systems  2017  18121.000000  17663.000000           NaN
14    Cisco Systems  2018  19225.000000  18121.000000  17663.000000
15    Cisco Systems  2019  18575.000000  19225.000000  18121.000000
16    Cisco Systems  2020  17206.000000  18575.000000  19225.000000
...             ...   ...           ...           ...           ...
2083         Xiaomi  2023   3608.428571  31779.470000  36917.050000
2084         Xiaomi  2024   3752.678571   3608.428571  31779.470000
2085         Xiaomi  2025   3896.928571   3752.678571   3608.428571
2086         Xiaomi  2026   4041.178571   3896.928571   3752.678571
2087         Xiaomi  2027   4185.428571   4041.178571   3896.928571

[1116 rows x 5 columns]

In [111]:
revenue = pd.read_csv("DATA/revenue_complete.csv")
revenue.Company = revenue.Company.apply(mapping_companies)
revenue = revenue[~revenue['Company'].isnull()]
revenue["Revenue_1"] = revenue.groupby('Company')['Revenue'].shift(1)
revenue["Revenue_2"] = revenue.groupby('Company')['Revenue'].shift(2)
revenue

            Company  Year   Revenue  Revenue_1  Revenue_2
12    Cisco Systems  2016  48570.00        NaN        NaN
13    Cisco Systems  2017  48096.00   48570.00        NaN
14    Cisco Systems  2018  50825.00   48096.00   48570.00
15    Cisco Systems  2019  51550.00   50825.00   48096.00
16    Cisco Systems  2020  48026.00   51550.00   50825.00
...             ...   ...       ...        ...        ...
2071         Xiaomi  2023  37203.67   38292.40   44892.10
2072         Xiaomi  2024   2419.43   37203.67   38292.40
2073         Xiaomi  2025  46869.64    2419.43   37203.67
2074         Xiaomi  2026  47776.38   46869.64    2419.43
2075         Xiaomi  2027  50536.69   47776.38   46869.64

[1116 rows x 5 columns]

In [112]:
final_df = merged_dataset.merge(cogs, how = "left", on = ["Company", "Year"]).merge(revenue, how = "left", on = ["Company", "Year"]).merge(ebitda, how = "left", on = ["Company", "Year"])
final_df = final_df[~final_df['Cogs'].isnull()].reset_index(drop = True)
final_df

,Company,Device,Market,SubMarket,Year,Value,Spendings,DevSpends,MarketSpends,SubMarketSpends,Cogs,Cogs_1,Cogs_2,Revenue,Revenue_1,Revenue_2,Ebitda,Ebitda_1,Ebitda_2
0,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2018,1.349324,63.254,33009.633,202444.977,52627.040,3186.310000,2861.370000,2547.60,4845.90,4300.20,3840.1,1261.600000,1068.200000,1007.2
1,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2019,1.491100,58.716,31492.062,190906.584,48480.544,3370.900000,3186.310000,2861.37,5158.60,4845.90,4300.2,1411.400000,1261.600000,1068.2
2,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2020,1.362700,61.471,30177.791,197047.823,54473.792,2996.520000,3370.900000,3186.31,4540.00,5158.60,4845.9,1283.200000,1411.400000,1261.6
3,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2021,2.164928,84.752,39871.494,245502.837,72134.752,3633.900000,2996.520000,3370.90,5546.50,4540.00,5158.6,1600.800000,1283.200000,1411.4
4,AMETEK,Amplifier/Comparator,Industrial,Manufacturing Equipment,2022,2.637800,88.482,44223.186,272578.716,80606.752,4005.260000,3633.900000,2996.52,6150.50,5546.50,4540.0,1820.100000,1600.800000,1283.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14800,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2020,0.809700,430.000,103400.887,212485.648,104836.024,2445.000000,2385.000000,2237.00,4448.00,4485.00,4218.0,831.000000,899.000000,817.0
14801,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2021,1.271038,546.000,128025.114,255121.403,125907.267,2999.000000,2445.000000,2385.00,5627.00,4448.00,4485.0,1198.000000,831.000000,899.0
14802,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2022,1.229600,517.000,138115.036,263200.273,122225.289,3157.000000,2999.000000,2445.00,5781.00,5627.00,4448.0,1140.000000,1198.000000,831.0
14803,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2023,1.182734,441.999,134477.314,214442.956,100072.931,17972.005714,3157.000000,2999.00,4536.76,5781.00,5627.0,2440.242857,1140.000000,1198.0
14804,Zebra Technologies,Voltage Regulator/Reference,Wireless Communications,Other Wireless,2024,1.173666,421.999,142579.443,195364.035,92275.977,18274.383929,17972.005714,3157.00,4671.88,4536.76,5781.0,916.760000,2440.242857,1140.0

In [113]:
final_df.to_csv("final_df.csv")

In [114]:
range(1, 2, 1)

range(1, 2)